### ISSUE TITLE
Bazel build fails on LiteRT v1.4.0

### ISSUE THREAD

**Issue by wajahat-abbas** [google-ai-edge/LiteRT#4530]
Hello,

I am trying to build target `//tflite:tensorflowlite` with Bazel but unsuccessful so far. Please see logs below. On a side note, I have tried building with docker also and result is the same.

I suspect this might be because the WORKSPACE file pins `org_tensorflow` to the tensorflow **master** branch. And If that’s the case, I’m a bit confused about how releases are expected to work, since the master branch changes constantly and could lead to dependency inconsistencies. This also possibly explains the issue seen by reporter in #3895.

I also tried building release v2.0.2 and it still fails.

```
LiteRT % bazel build -c dbg --config macos //tflite:tensorflowlite 
Starting local Bazel server and connecting to it...
WARNING: The following configs were expanded more than once: [apple-toolchain]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Reading 'startup' options from /Users/user/Workspace/test/LiteRT/.bazelrc: --windows_enable_symlinks
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=195
INFO: Reading rc options for 'build' from /Users/user/Workspace/test/LiteRT/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec --experimental_repo_remote_exec --noenable_bzlmod --noincompatible_enable_cc_toolchain_resolution --noincompatible_enable_android_toolchain_resolution
INFO: Reading rc options for 'build' from /Users/user/Workspace/test/LiteRT/.bazelrc:
  'build' options: --repo_env=USE_PYWRAP_RULES=True --copt=-DGRPC_BAZEL_BUILD --host_copt=-DGRPC_BAZEL_BUILD --action_env=GRPC_BAZEL_RUNTIME=1 --repo_env=PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=upb --action_env=PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=upb --repo_env=RULES_PYTHON_ENABLE_PYSTAR=0 --define framework_shared_object=true --define tsl_protobuf_header_only=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --features=-force_no_whole_archive --host_features=-force_no_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --experimental_cc_shared_library --experimental_link_static_libraries_once=false --incompatible_enforce_config_setting_visibility --config=v2 --config=litert_prefixes
INFO: Found applicable config definition build:short_logs in file /Users/user/Workspace/test/LiteRT/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /Users/user/Workspace/test/LiteRT/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:litert_prefixes in file /Users/user/Workspace/test/LiteRT/.bazelrc: --define=litert_prefixes=external/org_tensorflow/
INFO: Found applicable config definition build:macos in file /Users/user/Workspace/test/LiteRT/.bazelrc: --apple_platform_type=macos --copt=-DGRPC_BAZEL_BUILD --features=archive_param_file --linkopt=-Wl,-undefined,dynamic_lookup --host_linkopt=-Wl,-undefined,dynamic_lookup --config=apple-toolchain --copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++17 --host_cxxopt=-std=c++17
INFO: Found applicable config definition build:apple-toolchain in file /Users/user/Workspace/test/LiteRT/.bazelrc: --apple_crosstool_top=@local_config_apple_cc//:toolchain --crosstool_top=@local_config_apple_cc//:toolchain --host_crosstool_top=@local_config_apple_cc//:toolchain
INFO: Found applicable config definition build:macos in file /Users/user/Workspace/test/LiteRT/.bazelrc: --apple_platform_type=macos --copt=-DGRPC_BAZEL_BUILD --features=archive_param_file --linkopt=-Wl,-undefined,dynamic_lookup --host_linkopt=-Wl,-undefined,dynamic_lookup --config=apple-toolchain --copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++17 --host_cxxopt=-std=c++17
INFO: Found applicable config definition build:apple-toolchain in file /Users/user/Workspace/test/LiteRT/.bazelrc: --apple_crosstool_top=@local_config_apple_cc//:toolchain --crosstool_top=@local_config_apple_cc//:toolchain --host_crosstool_top=@local_config_apple_cc//:toolchain
DEBUG: /private/var/tmp/_bazel_user/84cb13b957679ff723be6edb7b19358c/external/local_xla/third_party/py/python_repo.bzl:84:14: !!!Using pywrap rules instead of directly creating .so objects!!!
DEBUG: /private/var/tmp/_bazel_user/84cb13b957679ff723be6edb7b19358c/external/local_xla/third_party/py/python_repo.bzl:89:10: 
=============================
Hermetic Python configuration:
Version: "3.12"
Kind: ""
Interpreter: "default" (provided by rules_python)
Requirements_lock label: "@python_version_repo//:requirements_lock_3_12.txt"
=====================================
ERROR: Error computing the main repository mapping: at /private/var/tmp/_bazel_user/84cb13b957679ff723be6edb7b19358c/external/org_tensorflow/tensorflow/workspace0.bzl:8:6: at /private/var/tmp/_bazel_user/84cb13b957679ff723be6edb7b19358c/external/com_github_grpc_grpc/bazel/grpc_extra_deps.bzl:27:6: cannot load '@@rules_java//java:rules_java_deps.bzl': no such file
Computing main repo mapping: 
    Fetching repository @@com_google_googleapis; starting
    Fetching repository @@envoy_api; starting
    Fetching repository @@com_google_protobuf; starting
    Fetching repository @@bazel_gazelle; starting
    Fetching repository @@build_bazel_rules_apple; starting
    Fetching repository @@com_envoyproxy_protoc_gen_validate; starting
    Fetching repository @@google_cloud_cpp; starting
    Fetching repository @@build_bazel_rules_swift; starting ... (24 fetches)
```

**Comment by aravindmurali22** [comment]
Hi @wajahat-abbas , thanks for filing this issue. The error `cannot load @@rules_java//java:rules_java_deps.bzl:  no such file` suggests there might be an issue with how the external dependencies are being resolved in your build environment.

Could you please run `bazel clean --expunge` and then try the build again. This will clear out any potentially corrupted cached artifacts. Additionally, to help us investigate this further, could you please provide the following information:
1. Bazel Version
2. Operating System
3. Xcode Version

Thanks.

**Comment by wajahat-abbas** [comment]
Thanks @aravindmurali22, I tried `bazel clean --expunge` and still getting same error. Please find below the versions you asked for.
```
Starting local Bazel server and connecting to it...
Build label: 7.4.1
Build target: @@//src/main/java/com/google/devtools/build/lib/bazel:BazelServer
Build time: Mon Nov 11 21:27:36 2024 (1731360456)
Build timestamp: 1731360456
Build timestamp as int: 1731360456

Xcode 26.1.1
Build version 17B100

ProductName:	macOS
ProductVersion:      15.6.1
BuildVersion:		24G90
```

**Comment by aravindmurali22** [comment]
Hi @wajahat-abbas , thank you for the response. I attempted to reproduce the issue on my macOS environment but was able to build the //tflite:tensorflowlite target successfully. Could you please try updating to the latest LiteRT version (v2.0.3)? Also, could you try running the build with the macOS SDK version explicitly set? This is the command that worked for me:

`bazel build -c dbg --config macos --macos_sdk_version=26.1 //tflite:tensorflowlite`

Am I missing any steps you took? Please let me know if that helps or if you have any more details.

**Comment by wajahat-abbas** [comment]
Thanks a lot @aravindmurali22, I tried release v2.0.3 with the command you shared but seeing issue related to flatbuffers version mismatch. I am sharing complete steps below, am I missing something?

Can you please confirm if you were able to build v1.4.0 successfully?

I am still confused how older releases are expected to work when Workspace file always pulls tensorflow master branch? Can you please help me understand this a bit.

```
syenaq02@JW5GJ7PWFJ test % git clone https://github.com/google-ai-edge/LiteRT.git
Cloning into 'LiteRT'...
remote: Enumerating objects: 47224, done.
remote: Counting objects: 100% (569/569), done.
remote: Compressing objects: 100% (223/223), done.
remote: Total 47224 (delta 425), reused 351 (delta 346), pack-reused 46655 (from 2)
Receiving objects: 100% (47224/47224), 328.18 MiB | 4.14 MiB/s, done.
Resolving deltas: 100% (33978/33978), done.
Updating files: 100% (7467/7467), done.
syenaq02@JW5GJ7PWFJ test % cd LiteRT 
syenaq02@JW5GJ7PWFJ LiteRT % git checkout v2.0.3
Note: switching to 'v2.0.3'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at b85cdce0 Merge pull request #4521 from dbcp1/2.0.3
syenaq02@JW5GJ7PWFJ LiteRT % ./configure
You have bazel 7.6.1 installed.
Please specify the location of python. [Default is /opt/homebrew/opt/python@3.13/bin/python3.13]: 


Found possible Python library paths:
  /opt/homebrew/lib/python3.13/site-packages
  /opt/homebrew/opt/python@3.13/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages
Please input the desired Python library path to use.  Default is [/opt/homebrew/lib/python3.13/site-packages]

Do you wish to build TensorFlow with ROCm support? [y/N]: N
No ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: N
No CUDA support will be enabled for TensorFlow.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -Wno-sign-compare]: 


Would you like to interactively configure ./WORKSPACE for Android builds? [y/N]: N
Not configuring the WORKSPACE for Android builds.

Do you wish to build TensorFlow with iOS support? [y/N]: N
No iOS support will be enabled for TensorFlow.

Preconfigured Bazel build configs. You can use any of the below by adding "--config=<>" to your build command. See .bazelrc for more details.
	--config=mkl         	# Build with MKL support.
	--config=mkl_aarch64 	# Build with oneDNN and Compute Library for the Arm Architecture (ACL).
	--config=monolithic  	# Config for mostly static monolithic build.
	--config=numa        	# Build with NUMA support.
	--config=dynamic_kernels	# (Experimental) Build kernels into separate shared objects.
	--config=v1          	# Build with TensorFlow 1 API instead of TF 2 API.
Preconfigured Bazel build configs to DISABLE default on features:
	--config=nogcp       	# Disable GCP support.
	--config=nonccl      	# Disable NVIDIA NCCL support.
Configuration finished
syenaq02@JW5GJ7PWFJ LiteRT % bazel clean --expunge                                 
Starting local Bazel server and connecting to it...
INFO: Reading 'startup' options from /Users/syenaq02/Workspace/test/LiteRT/.bazelrc: --windows_enable_symlinks
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=138
INFO: Reading rc options for 'clean' from /Users/syenaq02/Workspace/test/LiteRT/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec --experimental_repo_remote_exec --noenable_bzlmod
INFO: Reading rc options for 'clean' from /Users/syenaq02/Workspace/test/LiteRT/.bazelrc:
  Inherited 'build' options: --incompatible_enable_cc_toolchain_resolution --repo_env USE_HERMETIC_CC_TOOLCHAIN=1 --repo_env=USE_PYWRAP_RULES=True --copt=-DGRPC_BAZEL_BUILD --cxxopt=-std=gnu++17 --host_copt=-DGRPC_BAZEL_BUILD --action_env=GRPC_BAZEL_RUNTIME=1 --repo_env=PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=upb --action_env=PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=upb --repo_env=RULES_PYTHON_ENABLE_PYSTAR=0 --define framework_shared_object=true --define tsl_protobuf_header_only=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --features=-force_no_whole_archive --host_features=-force_no_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --experimental_cc_shared_library --experimental_link_static_libraries_once=false --incompatible_enforce_config_setting_visibility
INFO: Reading rc options for 'clean' from /Users/syenaq02/Workspace/test/LiteRT/.litert_configure.bazelrc:
  Inherited 'build' options: --action_env PYTHON_BIN_PATH=/opt/homebrew/opt/python@3.13/bin/python3.13 --action_env PYTHON_LIB_PATH=/opt/homebrew/lib/python3.13/site-packages --python_path=/opt/homebrew/opt/python@3.13/bin/python3.13
INFO: Reading rc options for 'clean' from /Users/syenaq02/Workspace/test/LiteRT/.bazelrc:
  Inherited 'build' options: --config=v2 --config=litert_prefixes --define=disable_tf_lite_py=true
INFO: Found applicable config definition build:short_logs in file /Users/syenaq02/Workspace/test/LiteRT/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /Users/syenaq02/Workspace/test/LiteRT/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:litert_prefixes in file /Users/syenaq02/Workspace/test/LiteRT/.bazelrc: --define=litert_prefixes=external/org_tensorflow/
INFO: Found applicable config definition build:macos in file /Users/syenaq02/Workspace/test/LiteRT/.bazelrc: --apple_platform_type=macos --copt=-DGRPC_BAZEL_BUILD --features=archive_param_file --linkopt=-Wl,-undefined,dynamic_lookup --host_linkopt=-Wl,-undefined,dynamic_lookup --config=apple-toolchain --copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++17 --host_cxxopt=-std=c++17
INFO: Found applicable config definition build:apple-toolchain in file /Users/syenaq02/Workspace/test/LiteRT/.bazelrc: --config=clang_local --apple_crosstool_top=@local_config_apple_cc//:toolchain --crosstool_top=@local_config_apple_cc//:toolchain --host_crosstool_top=@local_config_apple_cc//:toolchain
INFO: Found applicable config definition build:clang_local in file /Users/syenaq02/Workspace/test/LiteRT/.bazelrc: --noincompatible_enable_cc_toolchain_resolution --noincompatible_enable_android_toolchain_resolution --repo_env USE_HERMETIC_CC_TOOLCHAIN=0
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
syenaq02@JW5GJ7PWFJ LiteRT % bazel build -c dbg --config macos --macos_sdk_version=26.1 //tflite:tensorflowlite
Starting local Bazel server and connecting to it...
WARNING: The following configs were expanded more than once: [apple-toolchain, clang_local]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Reading 'startup' options from /Users/syenaq02/Workspace/test/LiteRT/.bazelrc: --windows_enable_symlinks
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=138
INFO: Reading rc options for 'build' from /Users/syenaq02/Workspace/test/LiteRT/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec --experimental_repo_remote_exec --noenable_bzlmod
INFO: Reading rc options for 'build' from /Users/syenaq02/Workspace/test/LiteRT/.bazelrc:
  'build' options: --incompatible_enable_cc_toolchain_resolution --repo_env USE_HERMETIC_CC_TOOLCHAIN=1 --repo_env=USE_PYWRAP_RULES=True --copt=-DGRPC_BAZEL_BUILD --cxxopt=-std=gnu++17 --host_copt=-DGRPC_BAZEL_BUILD --action_env=GRPC_BAZEL_RUNTIME=1 --repo_env=PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=upb --action_env=PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=upb --repo_env=RULES_PYTHON_ENABLE_PYSTAR=0 --define framework_shared_object=true --define tsl_protobuf_header_only=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --features=-force_no_whole_archive --host_features=-force_no_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --experimental_cc_shared_library --experimental_link_static_libraries_once=false --incompatible_enforce_config_setting_visibility
INFO: Reading rc options for 'build' from /Users/syenaq02/Workspace/test/LiteRT/.litert_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/opt/homebrew/opt/python@3.13/bin/python3.13 --action_env PYTHON_LIB_PATH=/opt/homebrew/lib/python3.13/site-packages --python_path=/opt/homebrew/opt/python@3.13/bin/python3.13
INFO: Reading rc options for 'build' from /Users/syenaq02/Workspace/test/LiteRT/.bazelrc:
  'build' options: --config=v2 --config=litert_prefixes --define=disable_tf_lite_py=true
INFO: Found applicable config definition build:short_logs in file /Users/syenaq02/Workspace/test/LiteRT/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /Users/syenaq02/Workspace/test/LiteRT/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:litert_prefixes in file /Users/syenaq02/Workspace/test/LiteRT/.bazelrc: --define=litert_prefixes=external/org_tensorflow/
INFO: Found applicable config definition build:macos in file /Users/syenaq02/Workspace/test/LiteRT/.bazelrc: --apple_platform_type=macos --copt=-DGRPC_BAZEL_BUILD --features=archive_param_file --linkopt=-Wl,-undefined,dynamic_lookup --host_linkopt=-Wl,-undefined,dynamic_lookup --config=apple-toolchain --copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++17 --host_cxxopt=-std=c++17
INFO: Found applicable config definition build:apple-toolchain in file /Users/syenaq02/Workspace/test/LiteRT/.bazelrc: --config=clang_local --apple_crosstool_top=@local_config_apple_cc//:toolchain --crosstool_top=@local_config_apple_cc//:toolchain --host_crosstool_top=@local_config_apple_cc//:toolchain
INFO: Found applicable config definition build:clang_local in file /Users/syenaq02/Workspace/test/LiteRT/.bazelrc: --noincompatible_enable_cc_toolchain_resolution --noincompatible_enable_android_toolchain_resolution --repo_env USE_HERMETIC_CC_TOOLCHAIN=0
INFO: Found applicable config definition build:macos in file /Users/syenaq02/Workspace/test/LiteRT/.bazelrc: --apple_platform_type=macos --copt=-DGRPC_BAZEL_BUILD --features=archive_param_file --linkopt=-Wl,-undefined,dynamic_lookup --host_linkopt=-Wl,-undefined,dynamic_lookup --config=apple-toolchain --copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++17 --host_cxxopt=-std=c++17
INFO: Found applicable config definition build:apple-toolchain in file /Users/syenaq02/Workspace/test/LiteRT/.bazelrc: --config=clang_local --apple_crosstool_top=@local_config_apple_cc//:toolchain --crosstool_top=@local_config_apple_cc//:toolchain --host_crosstool_top=@local_config_apple_cc//:toolchain
INFO: Found applicable config definition build:clang_local in file /Users/syenaq02/Workspace/test/LiteRT/.bazelrc: --noincompatible_enable_cc_toolchain_resolution --noincompatible_enable_android_toolchain_resolution --repo_env USE_HERMETIC_CC_TOOLCHAIN=0
DEBUG: /private/var/tmp/_bazel_syenaq02/84cb13b957679ff723be6edb7b19358c/external/local_xla/third_party/py/python_repo.bzl:158:14: 
HERMETIC_PYTHON_VERSION variable was not set correctly, using default version.
Python 3.13 will be used.
To select Python version, either set HERMETIC_PYTHON_VERSION env variable in
your shell:
  export HERMETIC_PYTHON_VERSION=3.12
OR pass it as an argument to bazel command directly or inside your .bazelrc
file:
  --repo_env=HERMETIC_PYTHON_VERSION=3.12
DEBUG: /private/var/tmp/_bazel_syenaq02/84cb13b957679ff723be6edb7b19358c/external/local_xla/third_party/py/python_repo.bzl:84:14: !!!Using pywrap rules instead of directly creating .so objects!!!
DEBUG: /private/var/tmp/_bazel_syenaq02/84cb13b957679ff723be6edb7b19358c/external/local_xla/third_party/py/python_repo.bzl:89:10: 
=============================
Hermetic Python configuration:
Version: "3.13"
Kind: ""
Interpreter: "default" (provided by rules_python)
Requirements_lock label: "@python_version_repo//:requirements_lock_3_13.txt"
=====================================
DEBUG: /private/var/tmp/_bazel_syenaq02/84cb13b957679ff723be6edb7b19358c/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'coremltools' because it already exists.
WARNING: The following configs were expanded more than once: [apple-toolchain, clang_local]. For repeatable flags, repeats are counted twice and may lead to unexpected behavior.
INFO: Analyzed target //tflite:tensorflowlite (156 packages loaded, 6806 targets configured).
ERROR: /Users/syenaq02/Workspace/test/LiteRT/tflite/converter/core/BUILD:24:11: Compiling tflite/converter/core/model_builder_base.cc failed: (Exit 1): wrapped_clang_pp failed: error executing CppCompile command (from target //tflite/converter/core:model_builder_base) bazel-out/darwin_arm64-opt-exec-ST-0465588ec812/bin/external/local_config_apple_cc/wrapped_clang_pp '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign ... (remaining 64 arguments skipped)
In file included from tflite/converter/core/model_builder_base.cc:15:
In file included from ./tflite/converter/core/model_builder_base.h:47:
./tflite/converter/schema/schema_generated.h:26:15: error: static assertion failed due to requirement '9 == 2': Non-compatible flatbuffers version included
   26 |               FLATBUFFERS_VERSION_MINOR == 2 &&
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
bazel-out/darwin_arm64-dbg/bin/external/flatbuffers/_virtual_includes/runtime_cc/flatbuffers/base.h:143:35: note: expanded from macro 'FLATBUFFERS_VERSION_MINOR'
  143 | #define FLATBUFFERS_VERSION_MINOR 9
      |                                   ^
1 error generated.
Error in child process '/usr/bin/xcrun'. 1
Target //tflite:tensorflowlite failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 91.765s, Critical Path: 7.50s
INFO: 1625 processes: 447 internal, 1178 local.
ERROR: Build did NOT complete successfully
```

**Comment by fergushenderson** [comment]
> I suspect this might be because the WORKSPACE file pins org_tensorflow to the tensorflow master branch. 

Yes, that was definitely a problem for build reproducibility.

The good news is that this has been fixed in LiteRT on master, which now pins `org_tensorflow` to a specific version.
See https://github.com/google-ai-edge/LiteRT/commit/7fc62273923827e9329b0a5c05c45d73df312309
and https://github.com/google-ai-edge/LiteRT/commit/7925eb956f3be5fae91b6c8c5b64156ad44fac5d.

**Comment by wajahat-abbas** [comment]
Thanks @fergushenderson, are there any plans to backport this fix to the previous releases? Because it seems that even the latest release i.e. `v2.0.3` pins tensorflow to master branch?

**Comment by fergushenderson** [comment]
> Thanks @fergushenderson, are there any plans to backport this fix to the previous releases?

Back porting this fix or something similar to 1.4.x and 2.x seems reasonable to me, to ensure reproducibility of the builds for those releases. Feel free to send a pull request.

But I can't speak for the LiteRT team's plans on that.  @niuchl or @terryheo may be able to answer that part of your question.

**Comment by fergushenderson** [comment]
Note that this issue is fixed in 2.1.0.

Backporting this fix to 1.4.x still seems like a good idea to me.  But as a work-around for the 1.* release series, the two patches identified in my earlier comment https://github.com/google-ai-edge/LiteRT/issues/4530#issuecomment-3552981661 should apply cleanly to the 1.4.1 sources.

**Comment by gunes-arm** [comment]
Thanks @fergushenderson

**Comment by aravindmurali22** [comment]
Hi @wajahat-abbas,

Apologies for late response. This issue has been resolved in LiteRT 2.1.0 and later releases. The TensorFlow workspace dependency in `WORKSPACE` is now pinned to an exact commit hash (`bcdab1a62e138c8f8784a7477c0be8af6dd0bd0a`) with SHA-256 verification and automated MSVC/Flatbuffers patches (`tensorflow_source_rules.bzl`).

Closing this issue. Please feel free to open a new issue if you encounter any issues on the latest releases!
